package com.link.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("T_LOG", "ID", TLog.class);
		arp.addMapping("T_MENU", "ID", TMenu.class);
		arp.addMapping("T_ORG", "ID", TOrg.class);
		arp.addMapping("T_PERMISSION", "ID", TPermission.class);
		arp.addMapping("T_ROLE", "ID", TRole.class);
		arp.addMapping("T_ROLE_MENU", "ID", TRoleMenu.class);
		arp.addMapping("T_ROLE_PERMISSION", "ID", TRolePermission.class);
		arp.addMapping("T_USER", "ID", TUser.class);
		arp.addMapping("T_USER_ORG", "ID", TUserOrg.class);
		arp.addMapping("T_USER_ROLE", "ID", TUserRole.class);
	}
}

