package com.link.model;

import com.link.model.base.BaseTLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TLog extends BaseTLog<TLog> {
	public static final TLog dao = new TLog().dao();
}
