package com.link.model;

import com.link.model.base.BaseTOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TOrg extends BaseTOrg<TOrg> {
	public static final TOrg dao = new TOrg().dao();
}
