package com.link.model;

import com.link.model.base.BaseTPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TPermission extends BaseTPermission<TPermission> {
	public static final TPermission dao = new TPermission().dao();
}
