package com.link.model;

import com.link.model.base.BaseTRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRolePermission extends BaseTRolePermission<TRolePermission> {
	public static final TRolePermission dao = new TRolePermission().dao();
}
