package com.link.model;

import com.link.model.base.BaseTRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRoleMenu extends BaseTRoleMenu<TRoleMenu> {
	public static final TRoleMenu dao = new TRoleMenu().dao();
}
