package com.link.model;

import com.link.model.base.BaseTUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUserRole extends BaseTUserRole<TUserRole> {
	public static final TUserRole dao = new TUserRole().dao();
}
