package com.link.model;

import com.link.model.base.BaseTUserOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUserOrg extends BaseTUserOrg<TUserOrg> {
	public static final TUserOrg dao = new TUserOrg().dao();
}
