package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTUserRole<M extends BaseTUserRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID");
	}

	public void setRoleId(java.lang.String roleId) {
		set("ROLE_ID", roleId);
	}

	public java.lang.String getRoleId() {
		return get("ROLE_ID");
	}

}
