package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChannel<M extends BaseChannel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setParent(java.lang.Integer parent) {
		set("parent", parent);
	}

	public java.lang.Integer getParent() {
		return get("parent");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setHide(java.lang.String hide) {
		set("hide", hide);
	}

	public java.lang.String getHide() {
		return get("hide");
	}

	public void setSorter(java.lang.Integer sorter) {
		set("sorter", sorter);
	}

	public java.lang.Integer getSorter() {
		return get("sorter");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}

	public java.lang.String getTarget() {
		return get("target");
	}

	public void setLoaded(java.lang.String loaded) {
		set("loaded", loaded);
	}

	public java.lang.String getLoaded() {
		return get("loaded");
	}

}
