package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTLog<M extends BaseTLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setActionkey(java.lang.String actionkey) {
		set("ACTIONKEY", actionkey);
	}

	public java.lang.String getActionkey() {
		return get("ACTIONKEY");
	}

	public void setOpertime(java.lang.String opertime) {
		set("OPERTIME", opertime);
	}

	public java.lang.String getOpertime() {
		return get("OPERTIME");
	}

	public void setIp(java.lang.String ip) {
		set("IP", ip);
	}

	public java.lang.String getIp() {
		return get("IP");
	}

	public void setUserid(java.lang.String userid) {
		set("USERID", userid);
	}

	public java.lang.String getUserid() {
		return get("USERID");
	}

	public void setUsername(java.lang.String username) {
		set("USERNAME", username);
	}

	public java.lang.String getUsername() {
		return get("USERNAME");
	}

	public void setParams(java.lang.String params) {
		set("PARAMS", params);
	}

	public java.lang.String getParams() {
		return get("PARAMS");
	}

	public void setResult(java.lang.String result) {
		set("RESULT", result);
	}

	public java.lang.String getResult() {
		return get("RESULT");
	}

}
