package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setActionkey(java.lang.String actionkey) {
		set("actionkey", actionkey);
	}

	public java.lang.String getActionkey() {
		return get("actionkey");
	}

	public void setOpertime(java.lang.String opertime) {
		set("opertime", opertime);
	}

	public java.lang.String getOpertime() {
		return get("opertime");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setParams(java.lang.String params) {
		set("params", params);
	}

	public java.lang.String getParams() {
		return get("params");
	}

	public void setResult(java.lang.String result) {
		set("result", result);
	}

	public java.lang.String getResult() {
		return get("result");
	}

}
