package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}

	public java.lang.String getIntro() {
		return get("intro");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}

	public java.lang.String getPid() {
		return get("pid");
	}

	public void setCreatedAt(java.lang.String createdAt) {
		set("created_at", createdAt);
	}

	public java.lang.String getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.lang.String updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.lang.String getUpdatedAt() {
		return get("updated_at");
	}

	public void setDeletedAt(java.lang.String deletedAt) {
		set("deleted_at", deletedAt);
	}

	public java.lang.String getDeletedAt() {
		return get("deleted_at");
	}

	public void setIsleaf(java.lang.String isleaf) {
		set("isleaf", isleaf);
	}

	public java.lang.String getIsleaf() {
		return get("isleaf");
	}

	public void setLoaded(java.lang.String loaded) {
		set("loaded", loaded);
	}

	public java.lang.String getLoaded() {
		return get("loaded");
	}

	public void setExpanded(java.lang.String expanded) {
		set("expanded", expanded);
	}

	public java.lang.String getExpanded() {
		return get("expanded");
	}

	public void setTreelevel(java.lang.Integer treelevel) {
		set("treelevel", treelevel);
	}

	public java.lang.Integer getTreelevel() {
		return get("treelevel");
	}

}
