package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTOrg<M extends BaseTOrg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setComcode(java.lang.String comcode) {
		set("COMCODE", comcode);
	}

	public java.lang.String getComcode() {
		return get("COMCODE");
	}

	public void setType(java.lang.String type) {
		set("TYPE", type);
	}

	public java.lang.String getType() {
		return get("TYPE");
	}

	public void setSortno(java.math.BigDecimal sortno) {
		set("SORTNO", sortno);
	}

	public java.math.BigDecimal getSortno() {
		return get("SORTNO");
	}

	public void setDesciption(java.lang.String desciption) {
		set("DESCIPTION", desciption);
	}

	public java.lang.String getDesciption() {
		return get("DESCIPTION");
	}

	public void setStatus(java.lang.String status) {
		set("STATUS", status);
	}

	public java.lang.String getStatus() {
		return get("STATUS");
	}

	public void setPid(java.lang.String pid) {
		set("PID", pid);
	}

	public java.lang.String getPid() {
		return get("PID");
	}

}
