package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}

	public java.lang.String getPid() {
		return get("pid");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setPageurl(java.lang.String pageurl) {
		set("pageurl", pageurl);
	}

	public java.lang.String getPageurl() {
		return get("pageurl");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setIsleaf(java.lang.String isleaf) {
		set("isleaf", isleaf);
	}

	public java.lang.String getIsleaf() {
		return get("isleaf");
	}

	public void setLoaded(java.lang.String loaded) {
		set("loaded", loaded);
	}

	public java.lang.String getLoaded() {
		return get("loaded");
	}

	public void setExpanded(java.lang.String expanded) {
		set("expanded", expanded);
	}

	public java.lang.String getExpanded() {
		return get("expanded");
	}

	public void setTreelevel(java.lang.Integer treelevel) {
		set("treelevel", treelevel);
	}

	public java.lang.Integer getTreelevel() {
		return get("treelevel");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

}
