package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTMenu<M extends BaseTMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setPid(java.lang.String pid) {
		set("PID", pid);
	}

	public java.lang.String getPid() {
		return get("PID");
	}

	public void setDescription(java.lang.String description) {
		set("DESCRIPTION", description);
	}

	public java.lang.String getDescription() {
		return get("DESCRIPTION");
	}

	public void setPageurl(java.lang.String pageurl) {
		set("PAGEURL", pageurl);
	}

	public java.lang.String getPageurl() {
		return get("PAGEURL");
	}

	public void setType(java.lang.String type) {
		set("TYPE", type);
	}

	public java.lang.String getType() {
		return get("TYPE");
	}

	public void setStatus(java.lang.String status) {
		set("STATUS", status);
	}

	public java.lang.String getStatus() {
		return get("STATUS");
	}

	public void setIsleaf(java.lang.String isleaf) {
		set("ISLEAF", isleaf);
	}

	public java.lang.String getIsleaf() {
		return get("ISLEAF");
	}

	public void setLoaded(java.lang.String loaded) {
		set("LOADED", loaded);
	}

	public java.lang.String getLoaded() {
		return get("LOADED");
	}

	public void setExpanded(java.lang.String expanded) {
		set("EXPANDED", expanded);
	}

	public java.lang.String getExpanded() {
		return get("EXPANDED");
	}

	public void setTreelevel(java.math.BigDecimal treelevel) {
		set("TREELEVEL", treelevel);
	}

	public java.math.BigDecimal getTreelevel() {
		return get("TREELEVEL");
	}

	public void setIcon(java.lang.String icon) {
		set("ICON", icon);
	}

	public java.lang.String getIcon() {
		return get("ICON");
	}

}
