package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTRole<M extends BaseTRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setValue(java.lang.String value) {
		set("VALUE", value);
	}

	public java.lang.String getValue() {
		return get("VALUE");
	}

	public void setIntro(java.lang.String intro) {
		set("INTRO", intro);
	}

	public java.lang.String getIntro() {
		return get("INTRO");
	}

	public void setPid(java.lang.String pid) {
		set("PID", pid);
	}

	public java.lang.String getPid() {
		return get("PID");
	}

	public void setCreatedAt(java.lang.String createdAt) {
		set("CREATED_AT", createdAt);
	}

	public java.lang.String getCreatedAt() {
		return get("CREATED_AT");
	}

	public void setUpdatedAt(java.lang.String updatedAt) {
		set("UPDATED_AT", updatedAt);
	}

	public java.lang.String getUpdatedAt() {
		return get("UPDATED_AT");
	}

	public void setDeletedAt(java.lang.String deletedAt) {
		set("DELETED_AT", deletedAt);
	}

	public java.lang.String getDeletedAt() {
		return get("DELETED_AT");
	}

}
