package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTUser<M extends BaseTUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setUsername(java.lang.String username) {
		set("USERNAME", username);
	}

	public java.lang.String getUsername() {
		return get("USERNAME");
	}

	public void setProvidername(java.lang.String providername) {
		set("PROVIDERNAME", providername);
	}

	public java.lang.String getProvidername() {
		return get("PROVIDERNAME");
	}

	public void setEmail(java.lang.String email) {
		set("EMAIL", email);
	}

	public java.lang.String getEmail() {
		return get("EMAIL");
	}

	public void setPhone(java.lang.String phone) {
		set("PHONE", phone);
	}

	public java.lang.String getPhone() {
		return get("PHONE");
	}

	public void setPassword(java.lang.String password) {
		set("PASSWORD", password);
	}

	public java.lang.String getPassword() {
		return get("PASSWORD");
	}

	public void setHasher(java.lang.String hasher) {
		set("HASHER", hasher);
	}

	public java.lang.String getHasher() {
		return get("HASHER");
	}

	public void setSalt(java.lang.String salt) {
		set("SALT", salt);
	}

	public java.lang.String getSalt() {
		return get("SALT");
	}

	public void setAvatarUrl(java.lang.String avatarUrl) {
		set("AVATAR_URL", avatarUrl);
	}

	public java.lang.String getAvatarUrl() {
		return get("AVATAR_URL");
	}

	public void setFirstName(java.lang.String firstName) {
		set("FIRST_NAME", firstName);
	}

	public java.lang.String getFirstName() {
		return get("FIRST_NAME");
	}

	public void setLastName(java.lang.String lastName) {
		set("LAST_NAME", lastName);
	}

	public java.lang.String getLastName() {
		return get("LAST_NAME");
	}

	public void setFullName(java.lang.String fullName) {
		set("FULL_NAME", fullName);
	}

	public java.lang.String getFullName() {
		return get("FULL_NAME");
	}

	public void setCreateAt(java.lang.String createAt) {
		set("CREATE_AT", createAt);
	}

	public java.lang.String getCreateAt() {
		return get("CREATE_AT");
	}

	public void setUpdateAt(java.lang.String updateAt) {
		set("UPDATE_AT", updateAt);
	}

	public java.lang.String getUpdateAt() {
		return get("UPDATE_AT");
	}

	public void setDeleteAt(java.lang.String deleteAt) {
		set("DELETE_AT", deleteAt);
	}

	public java.lang.String getDeleteAt() {
		return get("DELETE_AT");
	}

}
