package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}

	public java.lang.String getCid() {
		return get("cid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setView(java.lang.Integer view) {
		set("view", view);
	}

	public java.lang.Integer getView() {
		return get("view");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setHits(java.lang.String hits) {
		set("hits", hits);
	}

	public java.lang.String getHits() {
		return get("hits");
	}

	public void setGood(java.lang.String good) {
		set("good", good);
	}

	public java.lang.String getGood() {
		return get("good");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}

	public java.lang.String getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.lang.String modifytime) {
		set("modifytime", modifytime);
	}

	public java.lang.String getModifytime() {
		return get("modifytime");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("authorId", authorId);
	}

	public java.lang.String getAuthorId() {
		return get("authorId");
	}

	public void setAuthorName(java.lang.String authorName) {
		set("authorName", authorName);
	}

	public java.lang.String getAuthorName() {
		return get("authorName");
	}

	public void setSorter(java.lang.Integer sorter) {
		set("sorter", sorter);
	}

	public java.lang.Integer getSorter() {
		return get("sorter");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setBold(java.lang.String bold) {
		set("bold", bold);
	}

	public java.lang.String getBold() {
		return get("bold");
	}

	public void setItalic(java.lang.String italic) {
		set("italic", italic);
	}

	public java.lang.String getItalic() {
		return get("italic");
	}

	public void setColor(java.lang.String color) {
		set("color", color);
	}

	public java.lang.String getColor() {
		return get("color");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

}
